apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # adjust size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: image-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "abhishek@2003@sql"
            - name: DB_NAME
              value: "cloudcanvas_db"
            - name: JWT_SECRET
              value: "your_jwt_secret_key_here"
          volumeMounts:
            - name: uploads-volume
              mountPath: /uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: image-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30083
  type: NodePort
