apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
        - name: gallery
          image: gallery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "abhishek@2003@sql"
            - name: DB_NAME
              value: "cloudcanvas_db"
---
apiVersion: v1
kind: Service
metadata:
  name: gallery-service
spec:
  selector:
    app: gallery
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
